# Generated by Django 3.2.9 on 2022-03-02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(upload_to='media')),
                ('phone_no', models.IntegerField()),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=30)),
                ('pin_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(upload_to='media')),
                ('phone_no', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
    ]
